version: '3.7'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=parking-control-db
    ports:
      - '5435:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  db:
    driver: local